name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - pandas=1.4.4
  - plotly=5.9.0
  - numpy=1.26.4
  - wordcloud=1.8.2.2
  - matplotlib=3.5.2
  - nltk=3.7
  - scikit-learn=1.0.2
  - vaderSentiment=3.3.2
